DROP TABLE IF EXISTS `fwrp`.`user` CASCADE;
DROP TABLE IF EXISTS `fwrp`.`order` CASCADE;
DROP TABLE IF EXISTS `fwrp`.`subscription` CASCADE;
DROP TABLE IF EXISTS `fwrp`.`item` CASCADE;
DROP TABLE IF EXISTS `fwrp`.`notification` CASCADE;